//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    public partial class Discount
    {
        public int Discount_ID { get; set; }
        public double Discount_Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Product_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
    public class DiscountDbContext : DbContext
    {
        public DiscountDbContext() : base("name=UniqloEntities") // Ensure this matches your connection string in Web.config
        {
        }
        public DbSet<Product> Product { get; set; }
        public DbSet<Discount> Discount { get; set; }
    }
}
