//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations;

    public partial class Quantity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quantity()
        {
            this.OrderLists = new HashSet<OrderList>();
            this.WishlistItems = new HashSet<WishlistItem>();
        }
    
        public int Quantity_ID { get; set; }
        public int Product_ID { get; set; }
        public int Image_ID { get; set; }
        public string Color { get; set; }
        public int Qty { get; set; }
        public string Size { get; set; }
    
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderList> OrderLists { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishlistItem> WishlistItems { get; set; }

        public class ImageDbContext : DbContext
        {
            public ImageDbContext() : base("name=UniqloEntities") // Ensure this matches your connection string in Web.config
            {
            }

            public DbSet<Image> Image { get; set; } // Make sure 'Staff' is properly defined as a class
            public DbSet<Quantity> Quantities { get; set; }
            public DbSet<Product> Products { get; set; }

        }
    }
}
