//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity
    {
        public int Quantity_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity1 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
