//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    public partial class Review
    {
        public int Review_ID { get; set; }
        public int OrderList_ID { get; set; }
        public int Rating { get; set; }
        public string Review1 { get; set; }
        public System.DateTime Date_Submitted { get; set; }
    
        public virtual OrderList OrderList { get; set; }

        public class ReviewDbContext : DbContext
        {
            public ReviewDbContext() : base("name=UniqloEntities")
            {
            }

            public DbSet<Review> Review { get; set; }
        }
    }
}
