//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    public partial class Staff
    {
        [Key]
        public int Staff_ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
    public class StaffDbContext : DbContext
    {
        public StaffDbContext() : base("name=UniqloEntities") // Ensure this matches your connection string in Web.config
        {
        }

        public DbSet<Staff> Staff { get; set; } // Make sure 'Staff' is properly defined as a class
    }
}