//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniqlo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishlistItem
    {
        public int WishlistItem_ID { get; set; }
        public int Quantity_ID { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Quantity Quantity { get; set; }
    }
}
